### ISSUE TITLE
Wrong maven struture

### ISSUE THREAD

**Issue by exception** [yqt1001/FixedBlitzPowerups#1]
This plugin is not using a correct maven usage. If you're using intellij i suggest instead of creating / copy pasting your own pom and structure. You use the New -> Maven project and have it simpler. It is pretty simple to deduce that this structure is copy pasted over from somewhere since:
- Your pom.xml has wrong indent.
- Your pom.xml contains a manifest structure, which this plugin obviously doesn't have.

If you want to see a more complex maven project, take a look here https://github.com/beaconmc/Beacon/tree/master/bukkit-slave or here https://github.com/erosemberg/MineHack. 

Do _not_ take this issue as criticism, just someone giving a couple tips.

**Comment by yqt1001** [comment]
It is 100% copied from somewhere else, yeah. I believe with this project specifically I was just trying to get spigot 1.8 to compile (after 1.9 launch) and didn't really care how it worked. Thanks for bringing this up though!

**Comment by exception** [comment]
Yeah no problem, i was about to fork to make a couple fixes (eg wither dismounting being weird), but intellij hated the project and yeah.
